# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e09441b0194e4186dc514c6e5640d53d13b9eb3d4bd66f2c8dffa2b6f9a77a0e20dbb9cd7e1ff7b0337934658e7b991d7759a0e375da47efbbdacb5790f53aa9

test:
  secret_key_base: 65c319d7bf442798a229925de097abcc773c279aba9f9a45487e9a0d2d4fe44f4deb38d37b6d50e94a24abd86f2420f7687769f2e8ed91e17e87e8465c2b2331

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
